name: code_base
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # Navigation & deep linking
  auto_route: ^10.0.1

  # State management (BLoC)
  flutter_bloc: ^9.1.1

  # Value equality check
  equatable: ^2.0.7

  # API requests
  dio: ^5.8.0+1

  # Dependency injection
  get_it: ^8.0.3

  # Immutable data classes
  freezed_annotation: ^2.4.4

  # JSON serialization
  json_annotation: ^4.9.0

  cupertino_icons: ^1.0.8

  # Internet connection checker
  internet_connection_checker: ^1.0.0+1

  # Functional programming utilities
  dartz: ^0.10.1

  # API request logger
  pretty_dio_logger: ^1.4.0

  #chached image
  cached_network_image: ^3.4.0

  #shimmer
  shimmer: ^3.0.0

  # local cache
  shared_preferences: ^2.5.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Code generation
  build_runner: ^2.4.15

  # AutoRoute code generator
  auto_route_generator: ^10.0.1

  #code generator
  freezed: ^2.5.7

  # JSON serialization generator
  json_serializable: ^6.8.0


flutter:
  uses-material-design: true
  assets:
    - assets/png/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
