import 'package:flutter/material.dart';

class AppSpacing {
  AppSpacing._();

  static const horizontalSpacing0 = SizedBox(width: 0.0);
  static const horizontalSpacing2 = SizedBox(width: 2.0);
  static const horizontalSpacing4 = SizedBox(width: 4.0);
  static const horizontalSpacing6 = SizedBox(width: 6.0);
  static const horizontalSpacing8 = SizedBox(width: 8.0);
  static const horizontalSpacing10 = SizedBox(width: 10.0);
  static const horizontalSpacing12 = SizedBox(width: 12.0);
  static const horizontalSpacing14 = SizedBox(width: 14.0);
  static const horizontalSpacing16 = SizedBox(width: 16.0);
  static const horizontalSpacing18 = SizedBox(width: 18.0);
  static const horizontalSpacing20 = SizedBox(width: 20.0);
  static const horizontalSpacing22 = SizedBox(width: 22.0);
  static const horizontalSpacing24 = SizedBox(width: 24.0);
  static const horizontalSpacing26 = SizedBox(width: 26.0);
  static const horizontalSpacing28 = SizedBox(width: 28.0);
  static const horizontalSpacing30 = SizedBox(width: 30.0);
  static const horizontalSpacing32 = SizedBox(width: 32.0);
  static const horizontalSpacing34 = SizedBox(width: 34.0);
  static const horizontalSpacing36 = SizedBox(width: 36.0);
  static const horizontalSpacing38 = SizedBox(width: 38.0);
  static const horizontalSpacing40 = SizedBox(width: 40.0);
  static const horizontalSpacing46 = SizedBox(width: 46.0);
  static const horizontalSpacing48 = SizedBox(width: 48.0);
  static const horizontalSpacing56 = SizedBox(width: 56.0);

  static const verticalSpacing2 = SizedBox(height: 2.0);
  static const verticalSpacing4 = SizedBox(height: 4.0);
  static const verticalSpacing6 = SizedBox(height: 6.0);
  static const verticalSpacing8 = SizedBox(height: 8.0);
  static const verticalSpacing10 = SizedBox(height: 10.0);
  static const verticalSpacing12 = SizedBox(height: 12.0);
  static const verticalSpacing14 = SizedBox(height: 14.0);
  static const verticalSpacing16 = SizedBox(height: 16.0);
  static const verticalSpacing18 = SizedBox(height: 18.0);
  static const verticalSpacing20 = SizedBox(height: 20.0);
  static const verticalSpacing22 = SizedBox(height: 22.0);
  static const verticalSpacing24 = SizedBox(height: 24.0);
  static const verticalSpacing26 = SizedBox(height: 26.0);
  static const verticalSpacing28 = SizedBox(height: 28.0);
  static const verticalSpacing30 = SizedBox(height: 30.0);
  static const verticalSpacing32 = SizedBox(height: 32.0);
  static const verticalSpacing34 = SizedBox(height: 34.0);
  static const verticalSpacing36 = SizedBox(height: 36.0);
  static const verticalSpacing38 = SizedBox(height: 38.0);
  static const verticalSpacing40 = SizedBox(height: 40.0);
  static const verticalSpacing44 = SizedBox(height: 44.0);
  static const verticalSpacing46 = SizedBox(height: 46.0);
  static const verticalSpacing48 = SizedBox(height: 48.0);
  static const verticalSpacing50 = SizedBox(height: 50.0);
  static const verticalSpacing52 = SizedBox(height: 52.0);
  static const verticalSpacing54 = SizedBox(height: 54.0);
  static const verticalSpacing56 = SizedBox(height: 56.0);
  static const verticalSpacing60 = SizedBox(height: 60.0);
  static const verticalSpacing62 = SizedBox(height: 62.0);
  static const verticalSpacing64 = SizedBox(height: 64.0);
  static const verticalSpacing70 = SizedBox(height: 70.0);
  static const verticalSpacing72 = SizedBox(height: 72.0);
  static const verticalSpacing74 = SizedBox(height: 74.0);
  static const verticalSpacing76 = SizedBox(height: 76.0);
  static const verticalSpacing78 = SizedBox(height: 78.0);
  static const verticalSpacing80 = SizedBox(height: 80.0);
  static const verticalSpacing90 = SizedBox(height: 90.0);
  static const verticalSpacing96 = SizedBox(height: 96.0);
  static const verticalSpacing128 = SizedBox(height: 128.0);
}
